# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4706284172133aada4a07383a9dfb12871ae2d04e8efb758d5ee5f80f33011dc884dc0da17cc13d119cfb286674f3681c6e5bb670840c385db4e223897743915

test:
  secret_key_base: 73ecd90121a6d887435bd2ef5abf6ac6e946ce2af81add306430329f9e795a6259704531fa76c4292ae0aa4a203c27c32f5d9f8e0b6b662b8909745b5cb2785b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
